version: "3.8"

services:
  user-service:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres_container
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: securepassword
      DB_NAME: gymapp
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: gymapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
